<div>
	<div>
		<img src="http://teambrocolitv.com/wp-content/uploads/2016/11/teambrocolilogo2.png" alt="" width="100%" />
	</div>
	<div style="text-align: center;" >
		<div style="border: 0;color: inherit;display: block;font-size: 0.8em;letter-spacing: 0.225em;outline: 0;text-decoration: none;text-transform: uppercase;font-family: Arial;
		    font-weight: bold;
		    color: #31b23a;
		    margin: 2em 0em;" >
			HOLA <?= $fullname ?> , <br/>
			PARA CONFIRMAR TU CORREO ELECTRONICO HACE FALTA DARLE CLIC A CONFIRMAR <br/>
		</div>

		<a href="<?= $web ?>confirm/<?= $confirmation_code ?>" style="-moz-appearance: none;
																		    -webkit-appearance: none;
																		    -ms-appearance: none;
																		    appearance: none;
																		    -moz-transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
																		    -webkit-transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
																		    -ms-transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
																		    transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
																		    background-color: transparent;
																		    border-radius: 3px;
																		    border: 0;
																		    box-shadow: inset 0 0 0 2px #32d33a;
																		    color: #31b03a;
																		    cursor: pointer;
																		    display: inline-block;
																		    font-size: 0.8em;
																		    font-weight: 600;
																		    height: 3.125em;
																		    letter-spacing: 0.225em;
																		    line-height: 3.125em;
																		    padding: 0 2.75em;
																		    text-align: center;
																		    text-decoration: none;
																		    text-transform: uppercase;
																		    white-space: nowrap;
																		    overflow: hidden;
																		    text-overflow: ellipsis;border:1px solid #32d33a;" >CONFIRMAR</a>
	</div>
</div>